feat: import flatcar production OVA
mesosphere/vsphere-base-template pull request #7
Opened 2023-08-24 01:05 UTC by supershal

unlike RHEL and Ubuntu, flatcar publishes production OVA that can be used directly as base OS. https://lts.release.flatcar-linux.net/amd64-usr/3033.3.16/
This PR takes different approach for flatcar where it imports flatcar OVA instead of building it from ISO.

`make flatcar` target will directly download and import flatcar OVA to vCenter. 
@fatz Please let me know how to get these base templates to the release folder.

2023-08-24 05:41 UTC, fatz commented
so what I do not like is that this is completely ignoring the test layer. Furthermore it does not give any control about the vmware tooling or other things to take care of ( even though they might not be needed ATM )

So I wonder why we can't stick with the method of installing from ISO which allows us to keep this repository sort of agnostic as other private cloud solutions could easily be added during provisioning stage

2023-08-24 06:15 UTC, fatz commented on scripts/flatcar/import.sh
> +wget -O "${VM_NAME}.ova" -nv https://lts.release.flatcar-linux.net/amd64-usr/${FLATCAR_LTS_VERSION}/flatcar_production_vmware_ova.ova
this needs a checksum

2023-08-24 06:16 UTC, fatz commented on Makefile
> +	./scripts/flatcar/import.sh
when we already introduce a way to import OVA why not make it agnostic and add makefile targets for that import?

2023-08-24 06:18 UTC, fatz commented on Makefile
> +flatcar: $(GOVC)
testing is also missing here. Which means changes will not verify that flatcar build work like we expect them. We should keep the same quality level for flatcar as for every other distro.

2023-08-24 06:20 UTC, fatz commented on mkinclude/govc.mk
> +export GOVC ?= tmp/govc.bin
IMO this is not needed as the whole import.sh can be moved into a makefile target

2023-08-24 06:25 UTC, fatz requested changes
- If we really want to support OVA import that should have either a distro agnostic script or even better a make target which makes this procedure reusable.
- downloaded images must be checked against a checksum to ensure integrity
- testing must be applied to the imported image to ensure the image provides the same features as every other distro

2023-08-28 19:52 UTC, supershal commented
This PR is not needed. Alternative implementation: https://github.com/mesosphere/vsphere-base-template/pull/10

2023-08-28 19:52 UTC, closed without merging